"""
update_dashboard_data.py
=========================
sohyun 브랜치 분석 결과 → hyeonseo 대시보드 data.js/demand.js 업데이트

[업데이트 내용]
  demand.js: H3 셀별 Ds_v3(5변수 수요지수), Ra(로봇접근성) 추가
  data.js: GRID 배열의 urgency → Ds_v3 기반 cl(classification) 재분류
  hubs.js: 신규 거점 10개소 데이터 업데이트
"""

import pandas as pd
import numpy as np
import json
import subprocess
from pathlib import Path
from io import StringIO

BASE = Path(r"C:\Users\pasoh\OneDrive\문서\GitHub\Aero-Logic-seongnam")

print("=" * 60)
print("대시보드 데이터 업데이트 (sohyun → hyeonseo)")
print("=" * 60)

# ── sohyun 브랜치에서 CSV 읽기 ─────────────────────────────────────────────
def read_from_sohyun(filename):
    result = subprocess.run(
        ['git', 'show', f'sohyun:processed/{filename}'],
        capture_output=True, text=True, encoding='utf-8-sig',
        cwd=BASE
    )
    if result.returncode != 0:
        raise FileNotFoundError(f"sohyun:processed/{filename} 없음: {result.stderr}")
    return pd.read_csv(StringIO(result.stdout))

print("\n[1] sohyun 브랜치 CSV 로드...")
grid_df    = read_from_sohyun("constraint_layers_v3_ra.csv")
hubs_df    = read_from_sohyun("final_hubs_v2.csv")
mode_df    = read_from_sohyun("mode_comparison_v2.csv")
print(f"  grid: {len(grid_df)}행, hubs: {len(hubs_df)}행")

# ── Ds_v3 기반 분류 체계 ────────────────────────────────────────────────────
def classify_ds(ds_v3, composite):
    """기존 cl 분류를 Ds_v3 기반으로 재정의"""
    if composite == 0:
        return "부적합"
    if ds_v3 >= 0.6:
        return "최적"
    elif ds_v3 >= 0.45:
        return "높음"
    elif ds_v3 >= 0.30:
        return "보통"
    elif ds_v3 >= 0.15:
        return "낮음"
    else:
        return "부적합"

grid_df["cl_v3"] = grid_df.apply(
    lambda r: classify_ds(r["Ds_v3"], r.get("composite_score", r.get("composite_5layer", 0))),
    axis=1
)

print(f"\n  [Ds_v3 기반 분류 분포]")
print(grid_df["cl_v3"].value_counts().to_string())

# ── demand.js 생성 ─────────────────────────────────────────────────────────
print("\n[2] demand.js 생성...")

# H3 → 수요지수 매핑
demand_records = []
for _, row in grid_df.iterrows():
    demand_records.append({
        "h3"    : row["h3_index"],
        "ds3"   : round(float(row["Ds_v3"]),  4),
        "ra"    : round(float(row.get("Ra", 0)), 4),
        "hr"    : round(float(row.get("Hr", 0)), 4),
        "fp"    : round(float(row.get("Fp", 0)), 4),
        "cc"    : round(float(row.get("Cc", 0)), 4),
        "ec"    : round(float(row.get("Ec", 0)), 4),
        "od"    : round(float(row.get("Od_v2", row.get("Od", 0))), 4),
        "cl"    : row["cl_v3"],
    })

demand_js = f"""// Auto-generated by update_dashboard_data.py (sohyun analysis results)
// Updated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}
// Variables: Ds_v3 = 0.25×Hr + 0.20×Fp + 0.20×Cc + 0.20×Ec + 0.15×Od_v2
//            Ra  = 0.4×footway_ratio + 0.3×crossing + 0.3×walk_density
const DEMAND = {json.dumps(demand_records, ensure_ascii=False)};
"""

demand_path = BASE / "assets" / "js" / "demand.js"
demand_path.write_text(demand_js, encoding="utf-8")
print(f"  ✅ demand.js 저장 ({len(demand_records)}개 셀)")

# ── hubs_v2.js 생성 ────────────────────────────────────────────────────────
print("\n[3] hubs_v2.js 생성...")

hub_records = []
for _, row in hubs_df.iterrows():
    hub_records.append({
        "rank"        : int(row["step"]),
        "h3"          : row["h3_index"],
        "lat"         : round(float(row["lat"]), 6),
        "lon"         : round(float(row["lon"]), 6),
        "dong"        : row["ADM_NM"],
        "gu"          : row["GU_NM"],
        "ds3"         : round(float(row["Ds_v3"]), 4),
        "ra"          : round(float(row["Ra"]), 4),
        "cv2"         : round(float(row["composite_v2"]), 4),
        "new_covered" : int(row["new_covered"]),
        "coverage"    : round(float(row["coverage_pct"]) * 100, 1),
    })

hubs_js = f"""// Auto-generated — Greedy Set Cover 거점 (Ds_v3 + Ra 기반, 1km 반경)
// {len(hub_records)}개 거점, 최종 커버리지 {hub_records[-1]['coverage']:.1f}%
const HUBS_V2 = {json.dumps(hub_records, ensure_ascii=False, indent=2)};
"""

hubs_path = BASE / "assets" / "js" / "hubs_v2.js"
hubs_path.write_text(hubs_js, encoding="utf-8")
print(f"  ✅ hubs_v2.js 저장 ({len(hub_records)}개 거점)")

# ── ETA/배송모드 데이터 ────────────────────────────────────────────────────
print("\n[4] eta_data.js 생성...")

try:
    eta_df = read_from_sohyun("mode_comparison_v2.csv")
    eta_records = eta_df.to_dict("records")
    eta_js = f"""// Auto-generated — 배송 모드 비교 (NB12 ETA 시뮬레이션)
// 이착륙 4분, 신호대기 포함 현실적 ETA
const ETA_COMPARISON = {json.dumps(eta_records, ensure_ascii=False, indent=2)};
"""
    eta_path = BASE / "assets" / "js" / "eta_data.js"
    eta_path.write_text(eta_js, encoding="utf-8")
    print(f"  ✅ eta_data.js 저장 ({len(eta_records)}행)")
except Exception as e:
    print(f"  ⚠ eta_data.js 생략: {e}")

# ── demand.js와 GRID 연동 확인 (data.js의 h3 필드 샘플) ──────────────────
print("\n[5] data.js ↔ demand.js 연동 검증...")

# data.js에서 h3 인덱스 추출
data_js_content = (BASE / "assets" / "js" / "data.js").read_text(encoding="utf-8")
import re
h3_in_grid = set(re.findall(r'"h3":"([^"]+)"', data_js_content))
h3_in_demand = {r["h3"] for r in demand_records}

matched = h3_in_grid & h3_in_demand
print(f"  GRID H3: {len(h3_in_grid)}개")
print(f"  DEMAND H3: {len(h3_in_demand)}개")
print(f"  매칭: {len(matched)}개 ({len(matched)/max(len(h3_in_grid),1)*100:.1f}%)")

if len(matched) < len(h3_in_grid) * 0.5:
    print("  ⚠ 매칭률이 낮음 — H3 인덱스 불일치 가능성")
else:
    print("  ✅ 연동 정상")

print(f"\n✅ 대시보드 데이터 업데이트 완료!")
print(f"   - assets/js/demand.js: 5변수 수요지수 + Ra")
print(f"   - assets/js/hubs_v2.js: 신규 거점 10개")
print(f"   - assets/js/eta_data.js: ETA 비교 데이터")
print(f"\n   → dashboard.html에서 <script src='assets/js/demand.js'> 추가 필요!")
