"""
NB13_delivery_zone_classification.py
======================================
드론전용 / 로봇전용 / Hybrid 구역 분류 (Zoning)

회의 결의 로직:
  드론 전용   : composite_v2 > 0.45 AND Ra < 0.35
                → 드론 비행 가능 + 로봇 접근 어려움
  로봇 전용   : Ra > 0.55 AND Ds_v3 > 0.20 AND composite_v2 < 0.30
                → 보도 환경 우수 + 비행 제한/불필요
  Hybrid      : composite_v2 > 0.35 AND Ra > 0.40
                → 드론+로봇 모두 운영 가능 → 환승 최적지
  부적합      : 위 조건 불충족 또는 composite_v2 == 0

산출물:
  processed/delivery_zones.csv
  assets/js/zones.js          ← 대시보드 지도 레이어
"""

import pandas as pd
import numpy as np
from pathlib import Path
import json
import warnings
warnings.filterwarnings("ignore")

BASE = Path(r"C:\Users\pasoh\OneDrive\문서\GitHub\Aero-Logic-seongnam")
OUT  = BASE / "processed"

print("=" * 60)
print("NB13 — 배송 구역 분류 (Zoning)")
print("=" * 60)

# ── 데이터 로드 ───────────────────────────────────────────────
df = pd.read_csv(OUT / "constraint_layers_v3_ra.csv")
print(f"로드: {len(df)}행")

# composite_score_v2 재계산 (NB10 v2와 동일 로직)
score_cols = ["score_airspace","score_obstacle","score_noise","score_terrain","score_weather"]
score_cols = [c for c in score_cols if c in df.columns]
df["composite_5layer"] = df[score_cols].prod(axis=1)
RA_WEIGHT = 0.15
df["composite_v2"] = (1 - RA_WEIGHT) * df["composite_5layer"] + RA_WEIGHT * df["Ra"]

# ── Zoning 분류 ───────────────────────────────────────────────
def classify_zone(row):
    cv2 = row["composite_v2"]
    ra  = row["Ra"]
    ds  = row["Ds_v3"]

    if cv2 == 0:
        return "부적합"

    # 드론 전용: 비행 OK + 로봇 접근 어려움
    is_drone_ok  = cv2 > 0.45
    is_robot_bad = ra < 0.35

    # 로봇 전용: 보도 우수 + 비행 부적합 or 불필요
    is_robot_ok  = ra > 0.55
    is_drone_bad = cv2 < 0.30
    is_demand    = ds > 0.20

    # Hybrid: 둘 다 가능 + 수요 있음
    is_hybrid = cv2 > 0.35 and ra > 0.40

    if is_drone_ok and is_robot_bad:
        return "드론전용"
    elif is_robot_ok and is_drone_bad and is_demand:
        return "로봇전용"
    elif is_hybrid:
        return "Hybrid"
    elif cv2 > 0:
        return "일반"
    else:
        return "부적합"

print("\n[1] 구역 분류 계산 중...")
df["zone"] = df.apply(classify_zone, axis=1)

zone_counts = df["zone"].value_counts()
print("\n[구역별 셀 수]")
for z, n in zone_counts.items():
    pct = n / len(df) * 100
    bar = "█" * int(pct / 2)
    print(f"  {z:8s}: {n:4d}개 ({pct:5.1f}%) {bar}")

# ── 구역별 평균 지표 ─────────────────────────────────────────
print("\n[구역별 평균 지표]")
stats = df.groupby("zone")[["Ds_v3","Ra","composite_v2","Ec","Od_v2"]].mean().round(3)
print(stats.to_string())

# ── 환승(Hybrid) 거점 후보 상세 ──────────────────────────────
hybrid_cells = df[df["zone"] == "Hybrid"].copy()
hybrid_cells = hybrid_cells.sort_values("Ds_v3", ascending=False)

print(f"\n[Hybrid 환승 후보 상위 10개]")
cols_show = ["ADM_NM","GU_NM","Ds_v3","Ra","composite_v2","zone"]
print(hybrid_cells[cols_show].head(10).to_string(index=False))

# ── 구별 Zoning 분포 ─────────────────────────────────────────
print("\n[구별 Zoning 분포]")
pivot = df.groupby(["GU_NM","zone"]).size().unstack(fill_value=0)
print(pivot.to_string())

# ── CSV 저장 ─────────────────────────────────────────────────
df.to_csv(OUT / "delivery_zones.csv", index=False, encoding="utf-8-sig")
print(f"\n✅ delivery_zones.csv 저장 ({len(df)}행)")

# ── zones.js 생성 (대시보드용) ────────────────────────────────
print("\n[2] zones.js 생성...")

ZONE_COLOR = {
    "드론전용" : "#42A5F5",   # 파란색
    "로봇전용" : "#66BB6A",   # 초록색
    "Hybrid"   : "#FFA726",   # 주황색
    "일반"     : "#B0BEC5",   # 회색
    "부적합"   : None,        # 지도 미표시
}

zone_records = []
for _, row in df.iterrows():
    if row["zone"] == "부적합":
        continue
    zone_records.append({
        "h3"   : row["h3_index"],
        "lat"  : round(float(row["lat"]), 6),
        "lon"  : round(float(row["lon"]), 6),
        "dong" : row["ADM_NM"],
        "gu"   : row["GU_NM"],
        "zone" : row["zone"],
        "color": ZONE_COLOR[row["zone"]],
        "ds3"  : round(float(row["Ds_v3"]), 3),
        "ra"   : round(float(row["Ra"]), 3),
        "cv2"  : round(float(row["composite_v2"]), 3),
    })

# 구역별 통계 요약
zone_summary = {}
for z in ["드론전용","로봇전용","Hybrid","일반"]:
    sub = [r for r in zone_records if r["zone"] == z]
    zone_summary[z] = {
        "count" : len(sub),
        "color" : ZONE_COLOR[z],
        "label" : {"드론전용":"🚁 드론 전용","로봇전용":"🤖 로봇 전용",
                   "Hybrid":"🔄 Hybrid(환승)","일반":"📦 일반"}[z],
    }

zones_js = f"""// Auto-generated by NB13_delivery_zone_classification.py
// 드론전용 / 로봇전용 / Hybrid 구역 분류
// 기준: composite_v2(드론 운영 가능성) × Ra(로봇 접근성) × Ds_v3(수요)
const ZONE_SUMMARY = {json.dumps(zone_summary, ensure_ascii=False, indent=2)};
const ZONES = {json.dumps(zone_records, ensure_ascii=False)};
"""

zones_path = BASE / "assets" / "js" / "zones.js"
zones_path.write_text(zones_js, encoding="utf-8")
print(f"✅ zones.js 저장 ({len(zone_records)}개 셀)")

# ── 시각화 ───────────────────────────────────────────────────
try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.patches as mpatches

    plt.rcParams["axes.unicode_minus"] = False
    try:
        plt.rcParams["font.family"] = "Malgun Gothic"
    except:
        pass

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))
    fig.suptitle("NB13 — 성남시 드론·로봇 배송 구역 분류 (Zoning)", fontsize=13)

    # 파이 차트
    ax = axes[0]
    zones_plot = df[df["zone"] != "부적합"]["zone"].value_counts()
    colors_plot = [ZONE_COLOR.get(z, "#ccc") for z in zones_plot.index]
    ax.pie(zones_plot.values, labels=zones_plot.index, colors=colors_plot,
           autopct="%1.1f%%", startangle=90, textprops={"fontsize": 10})
    ax.set_title("구역 유형별 비율 (부적합 제외)")

    # 산점도: Ds_v3 vs Ra (구역별 색상)
    ax2 = axes[1]
    color_map = {"드론전용":"#42A5F5","로봇전용":"#66BB6A",
                 "Hybrid":"#FFA726","일반":"#B0BEC5","부적합":"#e0e0e0"}
    for zone_name, grp in df.groupby("zone"):
        ax2.scatter(grp["Ds_v3"], grp["Ra"],
                    c=color_map[zone_name], alpha=0.5, s=15,
                    label=zone_name, zorder=2 if zone_name != "부적합" else 1)
    # 구역 경계선 표시
    ax2.axvline(0.20, color="gray", ls=":", lw=0.8)
    ax2.axhline(0.40, color="gray", ls=":", lw=0.8)
    ax2.axhline(0.55, color="#66BB6A", ls="--", lw=0.8)
    ax2.set_xlabel("Ds_v3 (수요지수)")
    ax2.set_ylabel("Ra (로봇 접근성)")
    ax2.set_title("수요 × 로봇접근성 공간에서 Zoning")
    ax2.legend(markerscale=2, fontsize=9)
    ax2.grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig(OUT / "zoning_chart.png", dpi=150, bbox_inches="tight")
    print("✅ zoning_chart.png 저장")
except Exception as e:
    print(f"⚠ 차트 오류: {e}")

print(f"\n✅ NB13 완료!")
print(f"   - 드론전용: {zone_counts.get('드론전용',0)}셀")
print(f"   - 로봇전용: {zone_counts.get('로봇전용',0)}셀")
print(f"   - Hybrid:   {zone_counts.get('Hybrid',0)}셀")
print(f"   - 일반:     {zone_counts.get('일반',0)}셀")
print(f"   - 부적합:   {zone_counts.get('부적합',0)}셀")
